// starter-deck-b1.js — Kortpaket: 100 extremt användbara vardagsuttryck (B1).
// Franska → svenska. Stabila id:n (b1-NNN) → laddas idempotent, rör aldrig din historik.

export const STARTER_DECK_B1 = [
  // ---- Hälsningar & artighet ----
  { id: 'b1-001', front: 'Comment ça va ?', back: 'Hur är läget? / Hur mår du?', tags: ['hälsning', 'fråga'] },
  { id: 'b1-002', front: 'Ça va bien, merci.', back: 'Det är bra, tack.', tags: ['hälsning'] },
  { id: 'b1-003', front: 'Enchanté(e).', back: 'Trevligt att träffas.', tags: ['hälsning', 'artighet'] },
  { id: 'b1-004', front: 'Bienvenue !', back: 'Välkommen!', tags: ['hälsning'] },
  { id: 'b1-005', front: 'À tout à l\'heure.', back: 'Vi ses snart (senare idag).', tags: ['hälsning'] },
  { id: 'b1-006', front: 'À bientôt.', back: 'Vi ses snart.', tags: ['hälsning'] },
  { id: 'b1-007', front: 'Bonne journée !', back: 'Ha en bra dag!', tags: ['hälsning', 'artighet'] },
  { id: 'b1-008', front: 'Bonne soirée !', back: 'Ha en trevlig kväll!', tags: ['hälsning', 'artighet'] },
  { id: 'b1-009', front: 'Je vous en prie.', back: 'Varsågod / Ingen orsak (artigt).', tags: ['artighet'] },
  { id: 'b1-010', front: 'De rien.', back: 'Ingen orsak.', tags: ['artighet'] },
  { id: 'b1-011', front: 'Excusez-moi de vous déranger.', back: 'Ursäkta att jag stör.', tags: ['artighet'] },
  { id: 'b1-012', front: 'Pardon ?', back: 'Förlåt? / Vad sa du?', tags: ['artighet', 'fråga'] },

  // ---- Reaktioner ----
  { id: 'b1-013', front: "C'est pas grave.", back: 'Det gör inget.', tags: ['reaktion'] },
  { id: 'b1-014', front: 'Tant pis.', back: 'Det får vara / Synd då.', example: "Il n'y a plus de places ? Tant pis.", tags: ['reaktion'] },
  { id: 'b1-015', front: 'Tant mieux !', back: 'Vad bra! / Så mycket bättre!', tags: ['reaktion'] },
  { id: 'b1-016', front: 'Quelle bonne idée !', back: 'Vilken bra idé!', tags: ['reaktion'] },
  { id: 'b1-017', front: 'Avec plaisir.', back: 'Gärna / Med nöje.', tags: ['artighet', 'reaktion'] },
  { id: 'b1-018', front: 'Ça me va.', back: 'Det passar mig.', tags: ['reaktion'] },
  { id: 'b1-019', front: 'Pourquoi pas ?', back: 'Varför inte?', tags: ['reaktion'] },
  { id: 'b1-020', front: 'Bien sûr !', back: 'Självklart!', tags: ['reaktion'] },
  { id: 'b1-021', front: 'Tu as raison.', back: 'Du har rätt.', tags: ['reaktion', 'åsikt'] },
  { id: 'b1-022', front: "Je suis d'accord.", back: 'Jag håller med.', tags: ['åsikt'] },
  { id: 'b1-023', front: "Je ne suis pas d'accord.", back: 'Jag håller inte med.', tags: ['åsikt'] },
  { id: 'b1-024', front: "C'est vrai ?", back: 'Är det sant? / Jaså?', tags: ['reaktion'] },
  { id: 'b1-025', front: 'Ça alors !', back: 'Oj då! / Det var som tusan!', tags: ['reaktion'] },
  { id: 'b1-026', front: "C'est dommage.", back: 'Det är synd.', tags: ['reaktion'] },
  { id: 'b1-027', front: 'Félicitations !', back: 'Grattis!', tags: ['reaktion', 'artighet'] },

  // ---- Frågor & att klara sig ----
  { id: 'b1-028', front: "Pouvez-vous m'aider ?", back: 'Kan ni hjälpa mig?', tags: ['fråga', 'praktiskt'] },
  { id: 'b1-029', front: 'Pouvez-vous répéter, s\'il vous plaît ?', back: 'Kan ni upprepa, tack?', tags: ['fråga'] },
  { id: 'b1-030', front: 'Pouvez-vous parler plus lentement ?', back: 'Kan ni tala långsammare?', tags: ['fråga'] },
  { id: 'b1-031', front: "Comment on dit ça en français ?", back: 'Hur säger man det på franska?', tags: ['fråga'] },
  { id: 'b1-032', front: "Qu'est-ce que ça veut dire ?", back: 'Vad betyder det?', tags: ['fråga'] },
  { id: 'b1-033', front: 'Je ne comprends pas.', back: 'Jag förstår inte.', tags: ['fråga'] },
  { id: 'b1-034', front: 'Je ne sais pas.', back: 'Jag vet inte.', tags: ['fråga'] },
  { id: 'b1-035', front: 'Vous parlez anglais ?', back: 'Talar ni engelska?', tags: ['fråga', 'praktiskt'] },
  { id: 'b1-036', front: 'Où sont les toilettes ?', back: 'Var är toaletten?', tags: ['fråga', 'praktiskt'] },
  { id: 'b1-037', front: 'Combien ça coûte ?', back: 'Hur mycket kostar det?', tags: ['fråga', 'praktiskt'] },
  { id: 'b1-038', front: "Je voudrais un café, s'il vous plaît.", back: 'Jag skulle vilja ha en kaffe, tack.', tags: ['praktiskt'] },
  { id: 'b1-039', front: "L'addition, s'il vous plaît.", back: 'Notan, tack.', tags: ['praktiskt'] },
  { id: 'b1-040', front: 'Je peux payer par carte ?', back: 'Kan jag betala med kort?', tags: ['praktiskt', 'fråga'] },
  { id: 'b1-041', front: "Vous avez l'heure ?", back: 'Vet du vad klockan är?', tags: ['fråga', 'praktiskt'] },
  { id: 'b1-042', front: 'Je cherche la gare.', back: 'Jag letar efter stationen.', tags: ['praktiskt'] },
  { id: 'b1-043', front: "C'est loin d'ici ?", back: 'Är det långt härifrån?', tags: ['fråga', 'praktiskt'] },
  { id: 'b1-044', front: 'Je suis perdu(e).', back: 'Jag har gått vilse.', tags: ['praktiskt'] },
  { id: 'b1-045', front: "Un instant, s'il vous plaît.", back: 'Ett ögonblick, tack.', tags: ['artighet', 'praktiskt'] },

  // ---- Behov & tillstånd ----
  { id: 'b1-046', front: "J'ai faim.", back: 'Jag är hungrig.', tags: ['behov'] },
  { id: 'b1-047', front: "J'ai soif.", back: 'Jag är törstig.', tags: ['behov'] },
  { id: 'b1-048', front: 'Je suis fatigué(e).', back: 'Jag är trött.', tags: ['behov', 'känslor'] },
  { id: 'b1-049', front: 'Je suis pressé(e).', back: 'Jag har bråttom.', tags: ['behov'] },
  { id: 'b1-050', front: "J'ai froid.", back: 'Jag fryser.', tags: ['behov'] },
  { id: 'b1-051', front: "J'ai chaud.", back: 'Jag är varm.', tags: ['behov'] },
  { id: 'b1-052', front: 'Je suis malade.', back: 'Jag är sjuk.', tags: ['behov'] },
  { id: 'b1-053', front: 'Ça fait mal.', back: 'Det gör ont.', tags: ['behov'] },
  { id: 'b1-054', front: "J'ai besoin d'aide.", back: 'Jag behöver hjälp.', tags: ['behov', 'praktiskt'] },
  { id: 'b1-055', front: "Je n'ai pas le temps.", back: 'Jag har inte tid.', tags: ['behov', 'tid'] },
  { id: 'b1-056', front: "J'ai oublié.", back: 'Jag har glömt.', tags: ['vardag'] },
  { id: 'b1-057', front: 'Je suis désolé(e).', back: 'Jag är ledsen / Förlåt.', tags: ['artighet'] },
  { id: 'b1-058', front: "Ce n'est pas ma faute.", back: 'Det är inte mitt fel.', tags: ['reaktion'] },
  { id: 'b1-059', front: 'Je reviens tout de suite.', back: 'Jag kommer strax tillbaka.', tags: ['vardag'] },
  { id: 'b1-060', front: 'Attends-moi !', back: 'Vänta på mig!', tags: ['vardag'] },
  { id: 'b1-061', front: 'Dépêche-toi !', back: 'Skynda dig!', tags: ['vardag'] },
  { id: 'b1-062', front: 'Fais attention !', back: 'Var försiktig! / Akta!', tags: ['vardag'] },
  { id: 'b1-063', front: "Ne t'en fais pas.", back: 'Oroa dig inte.', tags: ['reaktion', 'känslor'] },
  { id: 'b1-064', front: 'Ça suffit !', back: 'Det räcker nu!', tags: ['reaktion'] },
  { id: 'b1-065', front: 'Laisse tomber.', back: 'Strunta i det / Glöm det.', example: "Ce n'est pas important, laisse tomber.", tags: ['reaktion'] },

  // ---- Småprat & åsikter ----
  { id: 'b1-066', front: "Qu'est-ce que tu en penses ?", back: 'Vad tycker du om det?', tags: ['småprat', 'åsikt', 'fråga'] },
  { id: 'b1-067', front: "Ça te dit d'aller au cinéma ?", back: 'Är du sugen på att gå på bio?', tags: ['småprat', 'fråga'] },
  { id: 'b1-068', front: 'On y va ?', back: 'Ska vi gå/köra?', tags: ['småprat'] },
  { id: 'b1-069', front: 'Je suis content(e) de te voir.', back: 'Jag är glad att se dig.', tags: ['småprat', 'känslor'] },
  { id: 'b1-070', front: "Comment s'est passée ta journée ?", back: 'Hur var din dag?', tags: ['småprat', 'fråga'] },
  { id: 'b1-071', front: "Qu'est-ce que tu fais ce week-end ?", back: 'Vad gör du i helgen?', tags: ['småprat', 'fråga'] },
  { id: 'b1-072', front: 'Ça fait plaisir !', back: 'Vad roligt! / Det gläder mig!', tags: ['reaktion', 'känslor'] },
  { id: 'b1-073', front: "Je m'ennuie.", back: 'Jag har tråkigt.', tags: ['känslor'] },
  { id: 'b1-074', front: "J'ai hâte !", back: 'Jag ser fram emot det! / Jag längtar!', tags: ['känslor'] },
  { id: 'b1-075', front: "C'est comme tu veux.", back: 'Som du vill.', tags: ['reaktion'] },
  { id: 'b1-076', front: 'Ça dépend.', back: 'Det beror på.', tags: ['reaktion'] },
  { id: 'b1-077', front: 'Peut-être.', back: 'Kanske.', tags: ['reaktion'] },
  { id: 'b1-078', front: 'J\'espère que oui.', back: 'Jag hoppas det.', tags: ['reaktion'] },
  { id: 'b1-079', front: 'Je crois que oui.', back: 'Jag tror det.', tags: ['reaktion', 'åsikt'] },
  { id: 'b1-080', front: "Je n'en ai aucune idée.", back: 'Jag har ingen aning.', tags: ['reaktion'] },

  // ---- Planer, telefon & praktiskt ----
  { id: 'b1-081', front: 'On se voit demain ?', back: 'Ses vi imorgon?', tags: ['plan', 'fråga'] },
  { id: 'b1-082', front: 'Tu es libre ce soir ?', back: 'Är du ledig ikväll?', tags: ['plan', 'fråga'] },
  { id: 'b1-083', front: 'Ça marche pour moi.', back: 'Det funkar för mig.', tags: ['plan', 'reaktion'] },
  { id: 'b1-084', front: 'Je te rappelle.', back: 'Jag ringer upp dig.', tags: ['telefon', 'plan'] },
  { id: 'b1-085', front: 'Tu peux me passer le sel ?', back: 'Kan du skicka saltet?', tags: ['praktiskt', 'fråga'] },
  { id: 'b1-086', front: 'Je peux te poser une question ?', back: 'Får jag fråga dig en sak?', tags: ['fråga'] },
  { id: 'b1-087', front: 'Tu peux me rendre un service ?', back: 'Kan du göra mig en tjänst?', tags: ['fråga', 'praktiskt'] },
  { id: 'b1-088', front: 'Ne quittez pas.', back: 'Dröj kvar (i telefon).', tags: ['telefon'] },
  { id: 'b1-089', front: "C'est de la part de qui ?", back: 'Vem är det som söker? (i telefon)', tags: ['telefon', 'fråga'] },
  { id: 'b1-090', front: 'Je vous le passe.', back: 'Jag kopplar er (vidare).', tags: ['telefon'] },
  { id: 'b1-091', front: 'Tiens-moi au courant.', back: 'Håll mig uppdaterad.', tags: ['plan'] },
  { id: 'b1-092', front: 'On verra plus tard.', back: 'Vi får se senare.', tags: ['plan'] },
  { id: 'b1-093', front: 'Ça ne fait rien.', back: 'Det gör inget.', tags: ['reaktion'] },
  { id: 'b1-094', front: "Comme d'habitude.", back: 'Som vanligt.', tags: ['vardag'] },
  { id: 'b1-095', front: 'À tout de suite.', back: 'Vi ses/hörs strax.', tags: ['hälsning'] },
  { id: 'b1-096', front: 'Tu rigoles ?', back: 'Skämtar du?', tags: ['reaktion'] },
  { id: 'b1-097', front: "C'est parti !", back: 'Nu kör vi! / Då sätter vi igång!', tags: ['reaktion'] },
  { id: 'b1-098', front: 'Bon courage !', back: 'Kämpa på! / Lycka till!', tags: ['artighet'] },
  { id: 'b1-099', front: 'Bonne chance !', back: 'Lycka till!', tags: ['artighet'] },
  { id: 'b1-100', front: 'Repose-toi bien.', back: 'Vila upp dig ordentligt.', tags: ['artighet'] },
];
