// starter-deck.js — Inbyggt startbibliotek: 100 användbara B2-fraser (franska → svenska).
// Fokus på muntlig produktion: konnektorer, åsikter, idiom och vardagsmeningar.
// Stabila id:n (starter-NNN) → laddas idempotent, skriver aldrig över din historik.

export const STARTER_DECK = [
  // ---- Konnektorer & diskursmarkörer ----
  { id: 'starter-001', front: "d'ailleurs", back: 'för övrigt / dessutom', tags: ['konnektor'] },
  { id: 'starter-002', front: 'en revanche', back: 'å andra sidan / däremot', tags: ['konnektor'] },
  { id: 'starter-003', front: 'par conséquent', back: 'följaktligen / därför', tags: ['konnektor'] },
  { id: 'starter-004', front: 'néanmoins', back: 'icke desto mindre / ändå', tags: ['konnektor'] },
  { id: 'starter-005', front: 'toutefois', back: 'emellertid / dock', tags: ['konnektor'] },
  { id: 'starter-006', front: 'en effet', back: 'ja just det / faktiskt (bekräftande)', tags: ['konnektor'] },
  { id: 'starter-007', front: 'or', back: 'men nu (övergång i ett resonemang)', tags: ['konnektor'] },
  { id: 'starter-008', front: 'ainsi', back: 'således / på så sätt', tags: ['konnektor'] },
  { id: 'starter-009', front: 'de ce fait', back: 'av den anledningen', tags: ['konnektor'] },
  { id: 'starter-010', front: "d'une part… d'autre part", back: 'å ena sidan … å andra sidan', tags: ['konnektor'] },
  { id: 'starter-011', front: 'au fur et à mesure', back: 'efter hand / allteftersom', tags: ['konnektor', 'uttryck'] },
  { id: 'starter-012', front: 'dans la mesure où', back: 'i den mån att / eftersom', tags: ['konnektor'] },
  { id: 'starter-013', front: 'à condition que', back: 'under förutsättning att', example: 'Je viendrai à condition que tu sois là.', tags: ['konnektor', 'subjonctif'] },
  { id: 'starter-014', front: 'bien que', back: 'fastän / även om', example: "Bien qu'il soit malade, il travaille.", tags: ['konnektor', 'subjonctif'] },
  { id: 'starter-015', front: 'afin que', back: 'för att / så att', example: 'Je parle lentement afin que tu comprennes.', tags: ['konnektor', 'subjonctif'] },
  { id: 'starter-016', front: 'tandis que', back: 'medan / medan däremot', tags: ['konnektor'] },
  { id: 'starter-017', front: 'dès que', back: 'så snart som', example: "Je t'appelle dès que j'arrive.", tags: ['konnektor'] },
  { id: 'starter-018', front: 'au cas où', back: 'i fall att / ifall', tags: ['konnektor'] },
  { id: 'starter-019', front: 'malgré', back: 'trots', example: 'Il est sorti malgré la pluie.', tags: ['konnektor'] },
  { id: 'starter-020', front: 'par ailleurs', back: 'för övrigt / dessutom', tags: ['konnektor'] },

  // ---- Åsikter & argumentation ----
  { id: 'starter-021', front: 'à mon avis', back: 'enligt min mening', tags: ['åsikt'] },
  { id: 'starter-022', front: 'il me semble que', back: 'det förefaller mig som att', tags: ['åsikt'] },
  { id: 'starter-023', front: 'je suis persuadé que', back: 'jag är övertygad om att', tags: ['åsikt'] },
  { id: 'starter-024', front: 'force est de constater que', back: 'man måste konstatera att', tags: ['åsikt'] },
  { id: 'starter-025', front: 'cela va sans dire', back: 'det säger sig självt', tags: ['åsikt', 'uttryck'] },
  { id: 'starter-026', front: "il n'empêche que", back: 'likväl förhåller det sig så att', tags: ['konnektor'] },
  { id: 'starter-027', front: 'je tiens à souligner que', back: 'jag vill betona att', tags: ['åsikt'] },
  { id: 'starter-028', front: 'autrement dit', back: 'med andra ord', tags: ['konnektor'] },
  { id: 'starter-029', front: "en d'autres termes", back: 'uttryckt på annat sätt', tags: ['konnektor'] },
  { id: 'starter-030', front: 'cela dit', back: 'med det sagt', tags: ['konnektor'] },
  { id: 'starter-031', front: 'à vrai dire', back: 'ärligt talat / sanningen att säga', tags: ['åsikt', 'uttryck'] },
  { id: 'starter-032', front: "dans l'ensemble", back: 'på det hela taget', tags: ['uttryck'] },
  { id: 'starter-033', front: 'en fin de compte', back: 'när allt kommer omkring', tags: ['uttryck'] },
  { id: 'starter-034', front: 'tout compte fait', back: 'allt sammantaget / när man tänker efter', tags: ['uttryck'] },
  { id: 'starter-035', front: 'quant à moi', back: 'vad mig beträffar', tags: ['åsikt', 'uttryck'] },

  // ---- Idiomatiska uttryck ----
  { id: 'starter-036', front: 'ça vaut le coup', back: 'det är värt besväret', tags: ['uttryck'] },
  { id: 'starter-037', front: "ça n'a rien à voir", back: 'det har inget med saken att göra', tags: ['uttryck'] },
  { id: 'starter-038', front: 'avoir le cafard', back: 'att vara nere / deppig', example: "Depuis qu'il est parti, j'ai le cafard.", tags: ['uttryck', 'känslor'] },
  { id: 'starter-039', front: "poser un lapin à quelqu'un", back: 'att svika en träff (inte dyka upp)', example: "Elle m'a posé un lapin hier soir.", tags: ['uttryck'] },
  { id: 'starter-040', front: 'coûter les yeux de la tête', back: 'att kosta skjortan', example: 'Cette voiture coûte les yeux de la tête.', tags: ['uttryck'] },
  { id: 'starter-041', front: 'tomber dans les pommes', back: 'att svimma', example: "Il faisait si chaud qu'elle est tombée dans les pommes.", tags: ['uttryck'] },
  { id: 'starter-042', front: 'avoir un coup de foudre', back: 'kärlek vid första ögonkastet', tags: ['uttryck', 'känslor'] },
  { id: 'starter-043', front: 'mettre de l\'eau dans son vin', back: 'att tona ner sina krav', example: "Avec le temps, il a mis de l'eau dans son vin.", tags: ['uttryck'] },
  { id: 'starter-044', front: 'faire la grasse matinée', back: 'att sova länge på morgonen', example: "Le dimanche, j'aime faire la grasse matinée.", tags: ['uttryck', 'vardag'] },
  { id: 'starter-045', front: 'revenir à ses moutons', back: 'att återgå till ämnet', example: 'Bref, revenons à nos moutons.', tags: ['uttryck'] },
  { id: 'starter-046', front: 'en avoir marre', back: 'att ha fått nog / vara trött på', example: "J'en ai marre de ce bruit.", tags: ['uttryck', 'känslor'] },
  { id: 'starter-047', front: 'ça marche', back: 'det funkar / ok då', tags: ['uttryck', 'vardag'] },
  { id: 'starter-048', front: "n'importe quoi", back: 'strunt / nonsens (eller: vad som helst)', tags: ['uttryck'] },
  { id: 'starter-049', front: 'au pied de la lettre', back: 'bokstavligt', example: 'Il a pris mes conseils au pied de la lettre.', tags: ['uttryck'] },
  { id: 'starter-050', front: 'prendre son courage à deux mains', back: 'att ta mod till sig', example: "J'ai pris mon courage à deux mains pour lui parler.", tags: ['uttryck'] },
  { id: 'starter-051', front: "avoir d'autres chats à fouetter", back: 'att ha annat att tänka på', example: "Désolé, j'ai d'autres chats à fouetter.", tags: ['uttryck'] },
  { id: 'starter-052', front: "casser les pieds à quelqu'un", back: 'att gå någon på nerverna', example: 'Arrête de me casser les pieds !', tags: ['uttryck'] },
  { id: 'starter-053', front: 'être à l\'aise', back: 'att känna sig bekväm', tags: ['uttryck'] },
  { id: 'starter-054', front: 'faire de son mieux', back: 'att göra sitt bästa', tags: ['uttryck'] },
  { id: 'starter-055', front: 'ça me dit quelque chose', back: 'det låter bekant', tags: ['uttryck'] },
  { id: 'starter-056', front: 'ça ne me dit rien', back: 'det lockar mig inte / jag är inte sugen', tags: ['uttryck'] },

  // ---- Vardagsmeningar ----
  { id: 'starter-057', front: "Je n'arrive pas à me décider.", back: 'Jag kan inte bestämma mig.', tags: ['vardag'] },
  { id: 'starter-058', front: 'Ça ne me dérange pas du tout.', back: 'Det stör mig inte alls.', tags: ['vardag'] },
  { id: 'starter-059', front: 'Tu aurais dû me prévenir.', back: 'Du borde ha sagt till mig.', tags: ['vardag'] },
  { id: 'starter-060', front: "Je m'en occupe tout de suite.", back: 'Jag tar hand om det med en gång.', tags: ['vardag'] },
  { id: 'starter-061', front: 'On ferait mieux de partir maintenant.', back: 'Vi borde nog gå nu.', tags: ['vardag'] },
  { id: 'starter-062', front: 'Ça dépend de ce que tu veux.', back: 'Det beror på vad du vill.', tags: ['vardag'] },
  { id: 'starter-063', front: "Je n'y avais pas pensé.", back: 'Det hade jag inte tänkt på.', tags: ['vardag'] },
  { id: 'starter-064', front: "Ne t'inquiète pas, je gère.", back: 'Oroa dig inte, jag fixar det.', tags: ['vardag'] },
  { id: 'starter-065', front: 'Je suis en train de le faire.', back: 'Jag håller på med det just nu.', tags: ['vardag'] },
  { id: 'starter-066', front: 'Il vaut mieux que tu y ailles.', back: 'Det är bäst att du går dit.', tags: ['vardag', 'subjonctif'] },
  { id: 'starter-067', front: 'Je te tiens au courant.', back: 'Jag håller dig uppdaterad.', tags: ['vardag'] },
  { id: 'starter-068', front: "Ça fait longtemps qu'on ne s'est pas vus.", back: 'Det var längesen vi sågs.', tags: ['vardag'] },
  { id: 'starter-069', front: "J'ai failli oublier.", back: 'Jag höll på att glömma.', tags: ['vardag'] },
  { id: 'starter-070', front: 'Tu peux compter sur moi.', back: 'Du kan räkna med mig.', tags: ['vardag'] },
  { id: 'starter-071', front: "Ça m'est égal.", back: 'Det gör mig detsamma.', tags: ['vardag'] },
  { id: 'starter-072', front: "Je n'en reviens pas.", back: 'Jag kan inte fatta det.', tags: ['vardag', 'känslor'] },
  { id: 'starter-073', front: 'Tu as raison sur ce point.', back: 'Du har rätt på den punkten.', tags: ['vardag', 'åsikt'] },
  { id: 'starter-074', front: 'Je ne sais pas quoi te dire.', back: 'Jag vet inte vad jag ska säga.', tags: ['vardag'] },
  { id: 'starter-075', front: 'On verra bien.', back: 'Vi får väl se.', tags: ['vardag'] },
  { id: 'starter-076', front: 'Ça tombe bien.', back: 'Det passar bra.', tags: ['vardag'] },
  { id: 'starter-077', front: "Je n'ai pas le temps de souffler.", back: 'Jag hinner inte dra andan.', tags: ['vardag'] },
  { id: 'starter-078', front: 'Fais comme chez toi.', back: 'Känn dig som hemma.', tags: ['vardag'] },
  { id: 'starter-079', front: "Ça ne sert à rien d'insister.", back: 'Det är ingen idé att tjata.', tags: ['vardag'] },
  { id: 'starter-080', front: 'Je suis débordé en ce moment.', back: 'Jag är överbelastad just nu.', tags: ['vardag'] },

  // ---- Hypoteser, känslor & mer abstrakt ----
  { id: 'starter-081', front: "Si j'avais su, je ne serais pas venu.", back: 'Om jag hade vetat hade jag inte kommit.', tags: ['hypotes'] },
  { id: 'starter-082', front: "J'aurais aimé pouvoir t'aider.", back: 'Jag hade önskat att jag kunnat hjälpa dig.', tags: ['hypotes'] },
  { id: 'starter-083', front: "Quoi qu'il arrive, je serai là.", back: 'Vad som än händer är jag där.', tags: ['hypotes', 'subjonctif'] },
  { id: 'starter-084', front: 'Il se peut que ce soit vrai.', back: 'Det kan hända att det är sant.', tags: ['hypotes', 'subjonctif'] },
  { id: 'starter-085', front: "Je crains qu'il ne soit trop tard.", back: 'Jag är rädd att det är för sent.', tags: ['hypotes', 'subjonctif'] },
  { id: 'starter-086', front: "Bien que ce soit difficile, j'y arriverai.", back: 'Även om det är svårt kommer jag att klara det.', tags: ['hypotes', 'subjonctif'] },
  { id: 'starter-087', front: 'À supposer que tu aies raison…', back: 'Antag att du har rätt …', tags: ['hypotes', 'subjonctif'] },
  { id: 'starter-088', front: "J'ai l'impression d'avoir tout gâché.", back: 'Jag känner att jag förstört allt.', tags: ['känslor'] },
  { id: 'starter-089', front: 'Ça me tient à cœur.', back: 'Det ligger mig varmt om hjärtat.', tags: ['känslor', 'uttryck'] },
  { id: 'starter-090', front: "Je ne m'attendais pas à ça.", back: 'Det hade jag inte väntat mig.', tags: ['känslor'] },
  { id: 'starter-091', front: "Plus j'y pense, moins je comprends.", back: 'Ju mer jag tänker på det, desto mindre förstår jag.', tags: ['uttryck'] },
  { id: 'starter-092', front: 'Cela me dépasse complètement.', back: 'Det går helt över mitt huvud.', tags: ['uttryck'] },
  { id: 'starter-093', front: 'Je suis partagé sur la question.', back: 'Jag är kluven i frågan.', tags: ['åsikt'] },
  { id: 'starter-094', front: 'Ça en valait la peine.', back: 'Det var värt det.', tags: ['uttryck'] },
  { id: 'starter-095', front: "Je n'aurais jamais cru ça possible.", back: 'Jag hade aldrig trott att det var möjligt.', tags: ['hypotes', 'känslor'] },
  { id: 'starter-096', front: "Il n'y a pas de quoi s'inquiéter.", back: 'Det finns inget att oroa sig för.', tags: ['vardag'] },
  { id: 'starter-097', front: 'Tout dépend du contexte.', back: 'Allt beror på sammanhanget.', tags: ['åsikt'] },
  { id: 'starter-098', front: "Je préfère ne pas m'avancer.", back: 'Jag vill helst inte uttala mig för tidigt.', tags: ['åsikt'] },
  { id: 'starter-099', front: 'Ça reste à voir.', back: 'Det återstår att se.', tags: ['uttryck'] },
  { id: 'starter-100', front: 'Mieux vaut tard que jamais.', back: 'Bättre sent än aldrig.', tags: ['uttryck'] },
];
